import { StyleSheet } from "react-native";

export default (theme: typeof import("../theme/colors").light) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.BACKGROUND,
      paddingTop: 16,
      paddingHorizontal: 18,
    },
    header: {
      fontSize: 28,
      fontWeight: "700",
      marginBottom: 2,
      color: theme.TEXT,
      fontFamily: "Inter",
    },
    subHeader: {
      fontSize: 16,
      color: theme.SUBTEXT,
      marginBottom: 6,
      fontFamily: "Inter",
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.ACCENT,
      marginVertical: 8,
      fontFamily: "Inter",
    },
    chip: {
      backgroundColor: theme.CHIP_BG,
      borderRadius: 50,
      paddingVertical: 8,
      paddingHorizontal: 18,
      marginRight: 10,
      borderWidth: 1,
      borderColor: theme.CHIP_BORDER,
    },
    chipText: {
      fontSize: 15,
      color: theme.ACCENT,
      fontWeight: "500",
      fontFamily: "Inter",
    },
    card: {
      width: 220,
      marginRight: 18,
      borderRadius: 22,
      backgroundColor: theme.CARD,
      overflow: "hidden",
      elevation: 2,
    },
    cardImage: {
      height: 120,
      width: "100%",
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme.TEXT,
      fontFamily: "Inter",
      marginBottom: 2,
    },
    cardDesc: {
      fontSize: 13,
      color: theme.SUBTEXT,
      marginBottom: 6,
      fontFamily: "Inter",
    },
    addBtn: {
      backgroundColor: theme.ACCENT,
      borderRadius: 100,
      alignSelf: "flex-start",
      paddingHorizontal: 14,
      paddingVertical: 6,
      marginTop: 4,
    },
    addBtnText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "600",
      fontFamily: "Inter",
    },
    cardSmall: {
      width: 110,
      marginRight: 12,
      borderRadius: 18,
      backgroundColor: theme.CHIP_BG,
      overflow: "hidden",
      elevation: 1,
      alignItems: "center",
    },
    cardImageSmall: {
      height: 64,
      width: "100%",
    },
    cardTitleSmall: {
      fontSize: 13,
      fontWeight: "600",
      color: theme.ACCENT,
      textAlign: "center",
      marginVertical: 5,
      fontFamily: "Inter",
    },
    banner: {
      backgroundColor: theme.CHIP_BORDER,
      borderRadius: 20,
      padding: 18,
      marginBottom: 14,
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
    },
    bannerText: {
      fontSize: 15,
      color: theme.TEXT,
      fontWeight: "500",
      flex: 1,
      fontFamily: "Inter",
    },
    bannerBtn: {
      backgroundColor: theme.ACCENT,
      borderRadius: 20,
      paddingVertical: 8,
      paddingHorizontal: 18,
      marginLeft: 16,
    },
    bannerBtnText: {
      color: "#fff",
      fontWeight: "600",
      fontSize: 15,
      fontFamily: "Inter",
    },
    aiBtn: {
      backgroundColor: theme.CARD,
      borderRadius: 16,
      paddingVertical: 14,
      alignItems: "center",
      marginTop: 20,
      marginBottom: 8,
      elevation: 1,
    },
    aiBtnText: {
      color: theme.ACCENT,
      fontWeight: "700",
      fontSize: 16,
      fontFamily: "Inter",
    },
    socialProof: {
      textAlign: "center",
      marginTop: 8,
      color: theme.ACCENT,
      fontWeight: "500",
      fontSize: 14,
      fontFamily: "Inter",
    },
    searchBox: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.CARD,
      borderRadius: 28, // Very rounded!
      paddingVertical: 16,
      paddingHorizontal: 18,
      marginBottom: 18,
      marginTop: 10,
      shadowColor: "#000",
      shadowOpacity: 0.1, // Subtle shadow
      shadowOffset: { width: 0, height: 3 },
      shadowRadius: 12,
      elevation: 4, // Android shadow
      borderColor: theme.CHIP_BORDER,
    },
    searchInput: {
      flex: 1,
      fontSize: 17,
      color: theme.TEXT,
      fontFamily: "Inter",
      fontWeight: "600",
      paddingVertical: 0, // For vertical centering
      backgroundColor: "transparent",
    },
  });
