import { StyleSheet } from "react-native";

export default (theme: typeof import("../theme/colors").light) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.BACKGROUND,
      paddingTop: 16,
      paddingHorizontal: 0,
    },
    searchBar: {
      marginHorizontal: 18,
      marginTop: 8,
      marginBottom: 10,
      backgroundColor: theme.CARD,
      borderRadius: 24,
      padding: 14,
      flexDirection: "row",
      alignItems: "center",
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 5 },
      elevation: 3,
    },
    searchText: {
      fontFamily: "Inter",
      fontSize: 17,
      color: theme.SUBTEXT,
      fontWeight: "500",
    },
    chipScroll: { marginTop: 8, maxHeight: 48, marginBottom: 12 },
    chipScrollContent: { paddingHorizontal: 18 },
    chip: {
      backgroundColor: theme.CHIP_BG,
      borderRadius: 18,
      paddingHorizontal: 18,
      paddingVertical: 8,
      marginRight: 10,
      marginBottom: 0,
    },
    chipText: {
      fontFamily: "Inter",
      fontSize: 17,
      color: theme.ACCENT,
      fontWeight: "600",
    },
    dealBanner: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme.ACCENT_CARD,
      borderRadius: 20,
      marginHorizontal: 18,
      paddingVertical: 16,
      paddingHorizontal: 18,
      marginBottom: 12,
      shadowColor: "#000",
      shadowOpacity: 0.06,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 2 },
    },
    dealText: {
      fontFamily: "Inter",
      fontSize: 16,
      color: theme.TEXT,
      fontWeight: "500",
      flex: 1,
      marginRight: 12,
    },
    dealBtn: {
      backgroundColor: theme.ACCENT,
      paddingVertical: 8,
      paddingHorizontal: 18,
      borderRadius: 12,
    },
    dealBtnText: {
      color: "#fff",
      fontWeight: "700",
      fontFamily: "Inter",
      fontSize: 16,
    },
    sectionTitle: {
      fontFamily: "Inter",
      fontWeight: "700",
      color: theme.ACCENT,
      fontSize: 20,
      marginHorizontal: 18,
      marginTop: 8,
      marginBottom: 6,
    },
    cardScroll: { marginBottom: 8 },
    cardScrollContent: { paddingHorizontal: 18 },
    card: {
      backgroundColor: theme.CARD,
      borderRadius: 22,
      overflow: "hidden",
      marginRight: 16,
      width: 180,
      height: 146,
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 2,
    },
    cardImg: {
      width: "100%",
      height: 90,
      resizeMode: "cover",
    },
    cardTextContainer: {
      paddingHorizontal: 10,
      paddingTop: 10,
    },
    cardTitle: {
      fontFamily: "Inter",
      fontWeight: "700",
      fontSize: 17,
      color: theme.TEXT,
    },
    cardDesc: {
      fontFamily: "Inter",
      fontSize: 15,
      color: theme.SUBTEXT,
      marginTop: 2,
    },
    // Small cards for "Nearby"
    cardSmall: {
      backgroundColor: theme.CARD,
      borderRadius: 18,
      overflow: "hidden",
      marginRight: 12,
      width: 110,
      height: 86,
      shadowColor: "#000",
      shadowOpacity: 0.07,
      shadowRadius: 7,
      shadowOffset: { width: 0, height: 3 },
      elevation: 1,
    },
    cardImgSmall: {
      width: "100%",
      height: 48,
      resizeMode: "cover",
    },
    cardTextContainerSmall: {
      paddingHorizontal: 8,
      paddingTop: 5,
    },
    cardTitleSmall: {
      fontFamily: "Inter",
      fontWeight: "700",
      fontSize: 15,
      color: theme.TEXT,
    },
    cardDescSmall: {
      fontFamily: "Inter",
      fontSize: 13,
      color: theme.SUBTEXT,
      marginTop: 2,
    },
    luckyBanner: {
      marginHorizontal: 18,
      marginTop: 16,
      marginBottom: 10,
      backgroundColor: theme.ACCENT_CARD,
      borderRadius: 16,
      paddingVertical: 18,
      paddingHorizontal: 18,
      alignItems: "center",
      justifyContent: "center",
    },
    luckyText: {
      fontFamily: "Inter",
      fontSize: 17,
      color: theme.ACCENT,
      fontWeight: "700",
      textAlign: "center",
    },
    bottomNotice: {
      marginTop: 0,
      marginHorizontal: 18,
      fontFamily: "Inter",
      fontSize: 15,
      color: theme.ACCENT,
      fontWeight: "500",
      textAlign: "center",
    },
  });
