// styles/plan.styles.ts

import { StyleSheet } from "react-native";
import * as colors from "../theme/colors";

export default (theme = colors.light) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.BACKGROUND,
      paddingHorizontal: 20,
      paddingTop: 32,
    },
    title: {
      fontSize: 32,
      fontWeight: "700",
      color: theme.TEXT,
      marginBottom: 4,
      fontFamily: "Inter",
    },
    subtitle: {
      fontSize: 16,
      color: theme.SUBTEXT,
      marginBottom: 24,
      fontFamily: "Inter",
    },
    tripListTitle: {
      fontSize: 20,
      color: theme.TEXT,
      fontWeight: "700",
      marginTop: 24,
      marginBottom: 8,
      fontFamily: "Inter",
    },
    tripCard: {
      backgroundColor: theme.CARD,
      borderRadius: 18,
      padding: 16,
      marginBottom: 14,
      shadowColor: "#000",
      shadowOpacity: 0.07,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 3 },
      elevation: 1,
    },
    tripName: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.TEXT,
      marginBottom: 2,
      fontFamily: "Inter",
    },
    tripDetails: {
      fontSize: 15,
      color: theme.SUBTEXT,
      marginBottom: 2,
      fontFamily: "Inter",
    },
    tripDate: {
      fontSize: 14,
      color: theme.SUBTEXT,
      fontFamily: "Inter",
    },
    addButton: {
      backgroundColor: theme.ACCENT,
      paddingVertical: 12,
      borderRadius: 14,
      alignItems: "center",
      marginTop: 24,
      marginBottom: 12,
    },
    addButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 17,
      fontFamily: "Inter",
    },
    // Modal
    modalContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: "rgba(0,0,0,0.25)",
    },
    modalContent: {
      backgroundColor: theme.CARD,
      padding: 24,
      borderRadius: 26,
      width: "90%",
      alignItems: "center",
      shadowColor: "#000",
      shadowOpacity: 0.12,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 6 },
      elevation: 8,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: theme.ACCENT,
      marginBottom: 22,
      fontFamily: "Inter",
    },
    input: {
      width: "100%",
      backgroundColor: theme.CARD,
      borderRadius: 12,
      padding: 14,
      fontSize: 16,
      marginBottom: 12,
      color: theme.TEXT,
      fontFamily: "Inter",
    },
    modalButtonRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      marginTop: 10,
    },
    modalButton: {
      flex: 1,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      marginHorizontal: 6,
      backgroundColor: theme.ACCENT,
    },
    modalButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 16,
      fontFamily: "Inter",
    },
    cancelButton: {
      backgroundColor: theme.CARD,
      borderWidth: 1,
      borderColor: theme.CHIP_BORDER,
    },
    cancelButtonText: {
      color: theme.TEXT,
    },
    errorText: {
      color: "#e74c3c",
      fontSize: 15,
      textAlign: "center",
      marginBottom: 8,
      marginTop: 4,
      fontFamily: "Inter",
    },
    emptyText: {
      color: theme.SUBTEXT,
      fontSize: 16,
      textAlign: "center",
      marginTop: 32,
      fontFamily: "Inter",
    },
    emptyTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: theme.TEXT,
      marginBottom: 6,
      fontFamily: "Inter",
    },
    emptySubtitle: {
      fontSize: 15,
      color: theme.SUBTEXT,
      marginBottom: 22,
      fontFamily: "Inter",
    },
    addBtn: {
      backgroundColor: theme.ACCENT,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      marginTop: 12,
      marginBottom: 20,
    },
    addBtnText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 16,
      fontFamily: "Inter",
    },
    card: {
      backgroundColor: theme.CARD,
      borderRadius: 14,
      padding: 16,
      marginBottom: 16,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.TEXT,
      marginBottom: 4,
      fontFamily: "Inter",
    },
    cardText: {
      fontSize: 15,
      color: theme.SUBTEXT,
      marginBottom: 6,
      fontFamily: "Inter",
    },
    cardNotes: {
      fontSize: 14,
      color: theme.ACCENT,
      marginTop: 2,
      fontFamily: "Inter",
    },
    aiButton: {
      backgroundColor: theme.ACCENT,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      marginTop: 12,
      marginBottom: 24,
    },
    aiButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontSize: 16,
      fontFamily: "Inter",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.38)",
      justifyContent: "center",
      alignItems: "center",
    },

    subTitle: {
      fontSize: 16,
      color: theme.SUBTEXT,
      marginBottom: 16,
      fontFamily: "Inter",
      textAlign: "center",
    },
    tripTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: theme.TEXT,
      fontFamily: "Inter",
      marginBottom: 2,
    },

    tripDates: {
      fontSize: 14,
      color: theme.SUBTEXT,
      fontFamily: "Inter",
      marginBottom: 6,
    },
  });
