import { StyleSheet } from "react-native";

export default (theme: typeof import("../theme/colors").light) =>
  StyleSheet.create({
    container: {
      paddingHorizontal: 18,
      paddingTop: 24,
      paddingBottom: 18,
      flexGrow: 1,
      backgroundColor: theme.BACKGROUND,
    },
    title: {
      fontSize: 26,
      fontWeight: "700",
      color: theme.TEXT,
      fontFamily: "Inter",
      marginBottom: 8,
    },
    subTitle: {
      fontSize: 16,
      color: theme.SUBTEXT,
      fontFamily: "Inter",
      marginBottom: 18,
    },
    card: {
      backgroundColor: theme.CARD,
      borderRadius: 18,
      padding: 20,
      marginBottom: 20,
      shadowColor: "#000",
      shadowOpacity: 0.08,
      shadowRadius: 10,
      elevation: 1,
    },
    cardTitle: {
      fontSize: 18,
      fontWeight: "600",
      color: theme.ACCENT,
      fontFamily: "Inter",
      marginBottom: 4,
    },
    cardText: {
      fontSize: 15,
      color: theme.TEXT,
      fontFamily: "Inter",
      marginBottom: 2,
    },
    cardNotes: {
      fontSize: 13,
      color: theme.SUBTEXT,
      fontFamily: "Inter",
      marginTop: 2,
      fontStyle: "italic",
    },
    aiButton: {
      marginTop: 18,
      backgroundColor: theme.ACCENT,
      borderRadius: 100,
      alignItems: "center",
      paddingVertical: 12,
    },
    aiButtonText: {
      color: "#fff",
      fontWeight: "700",
      fontFamily: "Inter",
      fontSize: 16,
    },
    errorText: {
      color: "#ff375f",
      fontSize: 15,
      marginBottom: 6,
      marginTop: 4,
      textAlign: "center",
      fontFamily: "Inter",
      fontWeight: "600",
    },
    emptyText: {
      color: theme.SUBTEXT,
      fontSize: 15,
      marginBottom: 16,
      textAlign: "center",
      fontFamily: "Inter",
    },
    // Modal styles
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.25)",
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      width: "90%",
      backgroundColor: theme.CARD,
      borderRadius: 20,
      padding: 22,
      shadowColor: "#000",
      shadowOpacity: 0.18,
      shadowRadius: 22,
      elevation: 8,
    },
    modalTitle: {
      fontSize: 20,
      fontFamily: "Inter",
      fontWeight: "700",
      color: theme.ACCENT,
      marginBottom: 12,
      textAlign: "center",
    },
    input: {
      width: "100%",
      height: 44,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.CHIP_BORDER,
      backgroundColor: theme.BACKGROUND,
      paddingHorizontal: 16,
      fontSize: 16,
      fontFamily: "Inter",
      marginBottom: 12,
      color: theme.TEXT,
    },
    modalButton: {
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      marginTop: 2,
    },
  });
